### ISSUE TITLE
BTCPay Dev Call #6

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/organization#69] opened 2021-11-23 19:30 UTC
```meta
Date: 2021-11-24
Time: 2:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-11-24 14:00 UTC
```

### Agenda

1. ...

### Check your timezone

https://everytimezone.com/s/b4628c4f

### Join the call

https://meet.jit.si/btcpayserverdev

### Calendar invite

Subscribe to the BTCPay Server calendar. More info [here](https://github.com/btcpayserver/organization#calendar).

**Comment by Zaxounette** [comment] 2021-11-24 15:16
**BTCPay Dev Call N°6 notes:**
**Attendees:** @ndeet, @satwo, @Kukks, @Zaxounette, @pavlenex, @dennisreimann, @NicolasDorier, @Wouter

----

**Docker-compose BTCPay Server edition**

Add plugins to such edition?
* In the CS proj, leave the reference to the plugin

LNBank will potentially need to have Greenfield extended in the plugin to create LN wallets.
Are the plugin API's going to be listed in the Greenfield API? 
* No 
Now that LNBank is integrated as plugin, we can create a store on a different BTCPay and link a LNBank sub account to it in a different BTCPay Server.
* This can be prevented with a header check

----

**Greenfield PHP library**
* First steps towards unit tests


----

**Woocommerce plugin refactoring**
* Worked on by Ndeet
* 90% done, looks good
  * Still some issues to figure out
* Early version before next release?
  * Yes, potentially

----

**Magento 2 plugin**
* Is there a marketplace for Magento plugins?
  * Yes, Wouter to look into it

----
**Next release highlights:**
* Plugins
  * LNBank
  * Sideshift (Coinswitch replacement as a plugin)
* Integrations

A simple readme page on each integration and they can be plugged into the docs.
We could also add option to deploy integrations when deploying BTCPay Server itself.

----

**Reviewing open PR's:**
* ETH support to be removed soon(TM) because has become abandoned
* Export checked invoice
  * Requires some UX changes
* Allow auto approval of pull payment claims
  * Will be worked on after 1.4.0 by Kukks
* Basic localization support
  * Checkout translations
    * This PR also checks for missing 
  * Should not be introduced before 1.6.0 once the dashboard is completed
  * Add the code in 1.5.0 and announce the translation request for 1.6.0
* LNURL Crowdfund app
  * Added to next release
* BC-UR v1 wallet support
  * Will become the go-to standard for exporting and importing HD wallets
* LNURL Auth
  * Add LNnode as a 2FA option
* Sign-in with other device
  * Adds possibility to log in from a phone
* Remove confirmed state in UI
  * Small issues left to figure out for this issue
    * Where to add the flag in the code for users to not see the warning again?
      * Warning should also not appear for newly deployed instances
* Test improvement
  * This test exposes something that doesn't work
  * Out tests actually don't test the right things
* Store-centric UI
  * Coming together nicely
  * Tests will work once the previous PR is fixed
* Allow pull-payments for store guests
  * Checks permissions both for the UI version, and the POST permissions

**Closed** 2021-11-24 18:11 UTC
Labels: call
